-- Overview (обзор ключевых метрик)
-- Total Sales, Total Profit, Profit Ratio, Avg. Discount
SELECT
  SUM(SALES) AS SALES_TOTAL,
  SUM(PROFIT) AS PROFIT_TOTAL,
  SUM(PROFIT) / SUM(SALES) * 100 AS PROFIT_RATIO,
  AVG(DISCOUNT) AS DISCOUNT_AVG
FROM ORDERS
;

-- Profit per Order
SELECT
  ORDER_ID,
  SUM(PROFIT) AS PROFIT
FROM ORDERS
GROUP BY ORDER_ID
;

-- Sales per Customer
SELECT
  CUSTOMER_ID,
  SUM(SALES) AS SALES
FROM ORDERS
GROUP BY CUSTOMER_ID
;

-- Monthly Sales by Segment
SELECT
  YEAR(ORDER_DATE) AS YEAR,
  MONTH(ORDER_DATE) AS MONTH,
  SEGMENT,
  SUM(SALES) AS SALES
FROM ORDERS
GROUP BY
  YEAR(ORDER_DATE),
  MONTH(ORDER_DATE),
  SEGMENT
ORDER BY
  YEAR,
  MONTH,
  SEGMENT
;

-- Monthly Sales by Product Category
SELECT
  YEAR(ORDER_DATE) AS YEAR,
  MONTH(ORDER_DATE) AS MONTH,
  CATEGORY,
  SUM(SALES) AS SALES
FROM ORDERS
GROUP BY
  YEAR(ORDER_DATE),
  MONTH(ORDER_DATE),
  CATEGORY
ORDER BY
  YEAR,
  MONTH,
  CATEGORY
;

-- Product Dashboard
-- Sales by Product Category over time
SELECT
  ORDER_DATE,
  CATEGORY,
  SUM(SALES) AS SALES
FROM ORDERS
GROUP BY
  ORDER_DATE,
  CATEGORY
ORDER BY
  ORDER_DATE,
  CATEGORY
;

-- Customer Analysis
-- Sales and Profit by Customer
SELECT
  CUSTOMER_ID,
  SUM(SALES) AS SALES,
  SUM(PROFIT) AS PROFIT
FROM ORDERS
GROUP BY CUSTOMER_ID
;

-- Customer Ranking
SELECT
  CUSTOMER_ID,
  DENSE_RANK() OVER (ORDER BY S.SALES) AS SALES_RUNK,
  DENSE_RANK() OVER (ORDER BY S.PROFIT) AS PROFIT_RUNK
FROM (
  SELECT
    CUSTOMER_ID,
    SUM(SALES) AS SALES,
    SUM(PROFIT) AS PROFIT
  FROM ORDERS
  GROUP BY CUSTOMER_ID
) S
;

-- Sales per region
SELECT
  REGION,
  SUM(SALES) AS SALES
FROM ORDERS
GROUP BY REGION
;













